### ISSUE TITLE
ciscoise_network_device_group encounter error to add device group

### ISSUE THREAD

**Issue by zlun26981** [CiscoISE/terraform-provider-ciscoise#100]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [ ] Do you have the latest Terraform provider version?
* [ ] Review the [compatibility matrix](https://github.com/CiscoISE/terraform-provider-ciscoise/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**

I'm trying to create network device group with ciscoise_network_device_group resource, however, it return error as 
" Invalid address to set: []string{"parameters", "0", "ndgtype"} "

**Expected behavior**

Create network device group

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.
![image](https://github.com/CiscoISE/terraform-provider-ciscoise/assets/23116381/7dff321b-c1f4-400f-ae36-efd2ed3e5aa9)

**Environment (please complete the following information):**
* ISE version and patch: 3.2P2
* Terraform version: 1.5.0
* ISE provider version: 0.6.20-beta
* OS version: CentOS 7

**Additional context**

**Comment by KubaMazurkiewicz** [comment]
Hey @zlun26981 this issue was fixed in 0.6.21-beta. Try latest provider version.

https://github.com/CiscoISE/terraform-provider-ciscoise/issues/94

**Comment by fmunozmiranda** [comment]
Closed due is already fixed.
