### ISSUE TITLE
ciscoise_sgt does not permit valid "-1" value for auto-generated SGT

### ISSUE THREAD

**Issue by grg1bbs** [CiscoISE/terraform-provider-ciscoise#109]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/CiscoISE/terraform-provider-ciscoise/tree/main#compatibility-matrix) before opening an issue. 

**Environment:**
* ISE version and patch: 3.1 patch 7 & 3.2 patch 4
* Terraform version: 1.6.4
* ISE provider version: 0.6.22-beta
* OS version: MacOS 13.6.1

**Describe the bug**
When using the 'ciscoise_sgt' resource to create a new SGT using an auto-generated number, the following error is returned:

│ Error: "parameters.0.value" cannot be lower than 2: -1
│ 
│   with ciscoise_sgt.sgt_shared_services,
│   on sgt.tf line 7, in resource "ciscoise_sgt" "sgt_shared_services":
│    7:     value = -1

**Expected behavior**
The "-1" value is a valid input for creating an auto-generated SGT number as per the API documentation, so the resource should allow this value.
https://developer.cisco.com/docs/identity-services-engine/latest/#!sgt

"value | Integer | Yes | Value range: 2 ot 65519 or **-1 to auto-generate**"

**Terraform code example**
```
resource "ciscoise_sgt" "sgt_shared_services" {
  provider = ciscoise.ise31-3
  parameters {
    name  = "Shared_Services"
    value = -1
  }
}
```

**Successful API call that returns a 201 response**
```
{
    "Sgt": {
        "name": "Shared_Services",
        "value": -1
    }
}
```

**Comment by grg1bbs** [comment]
@jbogarin can you please have a look into this issue? It seems like it should be a relatively quick and easy fix.
Thanks

**Comment by fmunozmiranda** [comment]
Tested in 0.8.1-beta and it´s working.
Closing issue, please reopen if you get some new trouble.
