### ISSUE TITLE
Cannot create ciscoise_network_device_group - othername/ndgtype issues.

### ISSUE THREAD

**Issue by mike-guy** [CiscoISE/terraform-provider-ciscoise#111]
# Describe the bug
The documentation for this resource says that the resource can use the following under parameters:

* description
* name
* ndgtype

But using ndgtype does not work. This appears to be a reintroduction of the error in #94 or it wasn't resolved. Additionally, the documentation still references "othername" in the example...

![image](https://github.com/CiscoISE/terraform-provider-ciscoise/assets/48997783/4c79574c-cdde-4f80-bf36-42b6e14e268f)

# Expected behaviour
Expected that the resource would be created, but it isn't.

# Screenshots

![image](https://github.com/CiscoISE/terraform-provider-ciscoise/assets/48997783/1ecdad1f-a7e2-46a8-8a63-01a1f54630ff)

# Actual behaviour
Error back from ISE API stating that the property name ndgtype is not correct.

![image](https://github.com/CiscoISE/terraform-provider-ciscoise/assets/48997783/d5470008-c931-4a96-951f-dbd8e598a6f8)

If I try and use othername in the resource, we get a terraform error instead stating this is not valid...

![image](https://github.com/CiscoISE/terraform-provider-ciscoise/assets/48997783/c7e8b7bf-2e53-4a68-a423-b731352c149d)

# Environment (please complete the following information):
* ISE version and patch: 3.3.0.430 (using dCloud sandbox)
* Terraform version: 1.7.3
* ISE provider version: 0.7.0-beta
* OS version: macOS 14.3.1

**Comment by kuba-mazurkiewicz** [comment]
Hey you can try using CiscoDevNet/ise provider: https://registry.terraform.io/providers/CiscoDevNet/ise/latest

TF code can look like this:

```
variable "group_names" {
  description = "List of group names"
  type        = list(string)
  default     = ["Group_1", "Group_2", "Group_3", "Group_4", "Group_5"]
}

resource "ise_network_device_group" "example" {
  for_each    = toset(var.group_names)
  name        = "Device Type#All Device Types#${each.key}"
  description = "My network device group"
  root_group  = "Device Type"
}
```

This will create following groups on ISE:

![Screenshot 2024-04-15 at 16 29 09](https://github.com/CiscoISE/terraform-provider-ciscoise/assets/132581633/bc8d088a-cdf5-46cc-b581-486063d6ee5c)

**Comment by fmunozmiranda** [comment]
Hi @mike-guy could you please retry it with last version of ISE provider and update us if bug still there?

**Comment by fmunozmiranda** [comment]
If we don´t get answer, this issue will be closed in next 24 hours.
