### ISSUE TITLE
Updating network device 

### ISSUE THREAD

**Issue by tali1974** [CiscoISE/terraform-provider-ciscoise#113]
**Prerequisites**
* [X] Have you tested the operation in the API directly?
* [X] Do you have the latest Terraform provider version?
* [X] Review the [compatibility matrix](https://github.com/CiscoISE/terraform-provider-ciscoise/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
I want to update an exist device.
When I use the rest API  like so it works just fine
`url = "https://192.168.10:9060/ers/config/networkdevice/"+devid
    response = requests.request("PUT", url, headers=headers, data=json.dumps(payload), verify=False)`
I am able to update an existing Network Device. But when I use 
`resource "ise_network_device" "ise_en" {  
  name                                          = "sw-003"
  description                                   = "EN"
  ips = [
    {
      ipaddress = "10.10.10.169"
      mask      = "32"
    }
  ]
  network_device_groups =[
    #"Location#All Locations#Test Sites",
    "Location#All Locations",
    "IPSEC#Is IPSEC Device#No",
    "Device Type#All Device Types#Switches",
  ]
  
}` I get error telling that the Device Name Already Exist
`Error: Client Error
│ 
│   with ise_network_device.ise_en,
│   on 000_Ipam.tf line 111, in resource "ise_network_device" "ise_en":
│  111: resource "ise_network_device" "ise_en" {
│ 
│ Failed to configure object (POST), got error: HTTP Request failed: StatusCode 400, Message: Network Device Create failed: Device Name Already Exist,`

**Expected behavior**

**Screenshots**

![SCR-20240422-tozc](https://github.com/CiscoISE/terraform-provider-ciscoise/assets/5436081/632d3317-e5e8-4a16-8ce8-736ef8edf93d)

**Environment (please complete the following information):**
* ISE version and patch:  3.1.0.518 (3,6)
* Terraform version: v1.5.0
* ISE provider version: 0.6.22-beta (0.7.0-beta)

**Additional context**

**Comment by fmunozmiranda** [comment]
Hi @tali1974 could you please retry it with last version of ISE provider and update us if bug still there?

**Comment by fmunozmiranda** [comment]
If we don´t get answer, this issue will be closed in next 24 hours.
