### ISSUE TITLE
Error - data source ciscoise_node_services_profiler_probe_config error

### ISSUE THREAD

**Issue by ragu2k8** [CiscoISE/terraform-provider-ciscoise#12]
ciscoise_node_services_profiler_probe_config (Data Source) resulting in below error
versions :  "0.1.0-rc.1",  "0.1.0-rc"

```
data "ciscoise_node_services_profiler_probe_config" "example" {
  provider = ciscoise
  hostname = "isenode1"
}

output "ciscoise_node_services_profiler_probe_config_example" {
  value = data.ciscoise_node_services_profiler_probe_config.example.item
}
```

Error:

```
Error: Failure when setting GetProfilerProbeConfig response
│ 
│   with data.ciscoise_node_services_profiler_probe_config.example,
│   on deployment.tf line 99, in data "ciscoise_node_services_profiler_probe_config" "example":
│   99: data "ciscoise_node_services_profiler_probe_config" "example" {
│ 
│ item.0.nmap: '' expected type 'string', got unconvertible type '[]interface {}'
```

It works with direct API:
```
{
  "response": {
    "netflow": null,
    "dhcp": {
      "interfaces": [
        {
          "interface": "GigabitEthernet 0"
        }
      ],
      "port": 67
    },
    "dhcpSpan": null,
    "http": {
      "interfaces": [
        {
          "interface": "GigabitEthernet 0"
        }
      ]
    },
    "radius": [],
    "nmap": [],
    "dns": {
      "timeout": 2
    },
    "snmpQuery": {
      "retries": 2,
      "timeout": 1000,
      "eventTimeout": 30
    },
    "snmpTrap": null,
    "activeDirectory": {
      "daysBeforeRescan": 1
    },
    "pxgrid": null
  },
  "version": "1.0.0"
}
```

**Comment by ragu2k8** [comment]
same error for for below,
ciscoise_tasks (Data Source)

 Error: Failure when setting GetAllTaskStatus response
│ 
│   with data.ciscoise_tasks.task_status,
│   on restore.tf line 17, in data "ciscoise_tasks" "task_status":
│   17: data "ciscoise_tasks" "task_status" {
│ 
│ items.0.detail_status: '' expected type 'string', got unconvertible type '[]interface {}'
╵
╷
│ Error: Failure when setting GetAllTaskStatus response
│ 
│   with data.ciscoise_tasks.task_status_all,
│   on restore.tf line 26, in data "ciscoise_tasks" "task_status_all":
│   26: data "ciscoise_tasks" "task_status_all" {
│ 
│ items.0.detail_status: '' expected type 'string', got unconvertible type '[]interface {}'
╵

**Comment by ragu2k8** [comment]
@wastorga  any help on this?

**Comment by wastorga** [comment]
Thanks for reporting the issue. I'm looking into it.
I'll update this issue once the new version is published.

**Comment by wastorga** [comment]
Version 0.1.0-rc.2 is currently in the process of publishing.
