### ISSUE TITLE
Dynamic urls in provider

### ISSUE THREAD

**Issue by ragu2k8** [CiscoISE/terraform-provider-ciscoise#16]
There is few APIs requires different base urls in provider config where it needs to talk to individual nodes directly in cluster(behaviour of product design at this point).. and requiring directory structure and provider config for each node is bit challenging(assuming we have 20+ nodes in a cluster) so is there any better way we can address it? i see terraform does not support dynamic urls in provider config.

Ex:
APIs
/api/v1/certs/system
/api/v1/hotpatch/install
/api/v1/patch/install 

Data Sources
ciscoise_hotpatch
ciscoise_hotpatch_install
ciscoise_hotpatch_rollback
ciscoise_patch
ciscoise_patch_install
ciscoise_patch_rollback
 Data Sources
ciscoise_system_certificate_import

**Comment by jbogarin** [comment]
@ragu2k8  let me see if I understand correctly.

What you are saying is that some APIs need to talk directly to the node and not the administration node and that you find the idea of creating a provider for each of those nodes, too cumbersome?

Is that right?

**Comment by ragu2k8** [comment]
yes thats correct.

**Comment by jbogarin** [comment]
Ok, I'll talk to the team, but not sure we can do anything. As you said, it is the way ISE works. I'll check to see if we can do anything to simplify it from within Terraform without adding too much complexity to the code base.

**Comment by jbogarin** [comment]
Check is this helps.

https://www.terraform.io/language/providers/configuration#alias-multiple-provider-configurations

**Comment by ragu2k8** [comment]
@jbogarin sure..i understand. Just wanted to ask and see if there is better way.
thanks for looking.

**Comment by ragu2k8** [comment]
> https://www.terraform.io/language/providers/configuration#alias-multiple-provider-configurations

yes thats one of the option

**Comment by ragu2k8** [comment]
> I think that's the best option because any other thing we come out with, we will have to ask the IP/FQDNs for each node and then ask to which node you want to talk to, which will end up being very similar to those aliases.

alright thanks for looking.
