### ISSUE TITLE
data source ciscoise_identity_group -crashing

### ISSUE THREAD

**Issue by ragu2k8** [CiscoISE/terraform-provider-ciscoise#20]
@wastorga
resource "ciscoise_identity_group" resulting in plugin crash..
`
ciscoise_identity_group.example: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with ciscoise_identity_group.example,
│   on main.tf line 16, in resource "ciscoise_identity_group" "example":
│   16: resource "ciscoise_identity_group" "example" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-ciscoise_v0.1.0-rc.4 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e91209]

goroutine 29 [running]:
terraform-provider-ciscoise/ciscoise.resourceIDentityGroupCreate(0x28261a0, 0xc000099260, 0xc000179c80, 0x2304d60, 0xc000781000, 0xc000e1e420, 0x12eb3da, 0xc000c9fc00)
	terraform-provider-ciscoise/ciscoise/resource_identity_group.go:118 +0xc9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000447340, 0x2826120, 0xc0001e3b40, 0xc000179c80, 0x2304d60, 0xc000781000, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.1/helper/schema/resource.go:330 +0x177
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000447340, 0x2826120, 0xc0001e3b40, 0xc000e66ee0, 0xc000c9fc00, 0x2304d60, 0xc000781000, 0x0, 0x0, 0x0, ...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.1/helper/schema/resource.go:456 +0x692
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0004a9a60, 0x2826120, 0xc0001e3b40, 0xc0010b54a0, 0xc0001e3b40, 0xc000098c00, 0x283de40)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.1/helper/schema/grpc_provider.go:955 +0x8b2
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000cd1d00, 0x2826120, 0xc0001e3b40, 0xc000e66cb0, 0xc000cd1d00, 0xc000e78bd0, 0xc000e63ba0)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0xac
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x24a7aa0, 0xc000cd1d00, 0x28261e0, 0xc000e78bd0, 0xc000098c00, 0x0, 0x28261e0, 0xc000e78bd0, 0xc0001ca2a0, 0xd3)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000318540, 0x2837960, 0xc000602600, 0xc0000aa200, 0xc000a9af30, 0x310cd00, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x50a
google.golang.org/grpc.(*Server).handleStream(0xc000318540, 0x2837960, 0xc000602600, 0xc0000aa200, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xcfd
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000362e0, 0xc000318540, 0x2837960, 0xc000602600, 0xc0000aa200)
	google.golang.org/grpc@v1.32.0/server.go:859 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x204

Error: The terraform-provider-ciscoise_v0.1.0-rc.4 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
`

**Comment by wastorga** [comment]
@ragu2k8 w
It seems you are not using the parameters. [Doc example](https://registry.terraform.io/providers/CiscoISE/ciscoise/latest/docs/resources/identity_group). [Sample](https://github.com/CiscoISE/terraform-provider-ciscoise/blob/main/examples/samples/resource_identity_group/main.tf).
I will try to change the parameters to be Required to avoid similar issues.

**Comment by ragu2k8** [comment]
Ok thanks
