### ISSUE TITLE
API response timeout setting

### ISSUE THREAD

**Issue by ragu2k8** [CiscoISE/terraform-provider-ciscoise#21]
@wastorga 
I have noticed one of the server did not respond to fetch patch status API request fast enough .API request was taking very long time ~>6mins and times out so its definitely an ISE server specific issue but however terraform also waits for long time, is it possible to configure timeout for rest calls in provider explicitly? i am not sure if its configurable in ISE SDK either.

![image](https://user-images.githubusercontent.com/17446630/152188673-86b66aa3-3389-4508-b4db-ca44d48f9696.png)

**Comment by wastorga** [comment]
Hi, @ragu2k8.
We are working on performing the necessary changes for your feature request. I'll update you here when we have them.

**Comment by wastorga** [comment]
I have implemented the change, and the release version is underway.

The provider configuration now has the single_request_timeout for this feature. 

Code extract is shown below.
```terraform
# Configure provider with your  Cisco Identity Services Engine SDK credentials
provider "ciscoise" {
  # ...
  # Timeout (in seconds) for the RESTful HTTP requests
  single_request_timeout = 60
  # it can be set using the environment variable ISE_SINGLE_REQUEST_TIMEOUT
}
```

**Comment by ragu2k8** [comment]
> I have implemented the change, and the release version is ~underway~ up.
> 
> The provider configuration now has the single_request_timeout for this feature.
> 
> Code extract is shown below.
> 
> ```terraform
> # Configure provider with your  Cisco Identity Services Engine SDK credentials
> provider "ciscoise" {
>   # ...
>   # Timeout (in seconds) for the RESTful HTTP requests
>   single_request_timeout = 60
>   # it can be set using the environment variable ISE_SINGLE_REQUEST_TIMEOUT
> }
> ```

cool.. you are awesome!!
