### ISSUE TITLE
ciscoise_pxgrid* APIs

### ISSUE THREAD

**Issue by ragu2k8** [CiscoISE/terraform-provider-ciscoise#24]
@wastorga Looks the documentation and provider config does not say much about using pxgrid apis as its different from other APIs and here we need to create pxgrid account which uses password based auth or cert based auth which generates client secret for further subsequent calls so just wondering if i missed something .

**Comment by wastorga** [comment]
Sorry for the delay. You can get more information here:

- https://github.com/cisco-pxgrid
- https://developer.cisco.com/site/pxgrid/
- https://cs.co/ise-guides > Cisco Platform Exchange Grid (pxGrid)

**Comment by wastorga** [comment]
@ragu2k8 ciscoise_pxgrid* have been removed in v0.2.0. They  have been classified as unsafe by the team.

**Comment by wastorga** [comment]
Next 0.3.0 version will transform some of them to resources.

**Comment by ragu2k8** [comment]
got it thanks.
