### ISSUE TITLE
ciscoise_active_directory_join_domain_with_all_nodes does not exist

### ISSUE THREAD

**Issue by ragu2k8** [CiscoISE/terraform-provider-ciscoise#27]
did we remove this recently ciscoise_active_directory_join_domain_with_all_nodes from data source ? it used to work with version 0.1.0-rc.4

**Comment by jbogarin** [comment]
We need to fix it. It used to be data source but that cause other issues. We are in the process of migrating that to a resource. It should be ready in the next couple of weeks.

Sorry for the trouble, but we found edge cases where having that (plus other operations as data sources) could cause problems in the infrastructure

**Comment by jbogarin** [comment]
We will let you know once the new version is uploaded with some of the operations migrated to resources.

**Comment by ragu2k8** [comment]
ok thanks for update

**Comment by fmunozmiranda** [comment]
@ragu2k8 there is a new version of terraform-provider-ciscoise (v0.4.0-beta), the operation was included, please try it and let know us if is working for you.

**Comment by bvargasre** [comment]
Hi @ragu2k8, is the problem solved?
If not, let us know, otherwise the issue will be closed due to inactivity.
