### ISSUE TITLE
Terraform did not correct a controlled resource.

### ISSUE THREAD

**Issue by RyanMBess** [CiscoISE/terraform-provider-ciscoise#47]
I ran the below 
```tf
resource "ciscoise_sgt" "example" {
  provider = ciscoise
  parameters {

    description       = "Terraform created with update"
    #generation_id     = "string123"
    #id                = "string987"
    is_read_only      = "false"
    name              = "TerraformSGT"
    propogate_to_apic = "false"
    value             = 18
  }
```

this created the SGT in ISE.  I then went into ISE and renamed it to TerraformSGT1.  Ran Terraform plan.  It saw the change but when i did the terraform apply nothing is updated.

**Comment by fmunozmiranda** [comment]
Het @RyanMBess ,there's a new provider version (0.6.6-beta). This behavior should be solved. Please try it again and let us know if it works for you.

**Comment by fmunozmiranda** [comment]
Hey @RyanMBess  if we don't get answer in next 24 hours, this issue will be close due inactivity.

**Comment by fmunozmiranda** [comment]
Closing due inactivity.
