### ISSUE TITLE
Correct Documentation For Required Attributes

### ISSUE THREAD

**Issue by RyanMBess** [CiscoISE/terraform-provider-ciscoise#48]
If you look at the Cisco Documentation they state what is required.  In this case SGTs require a name and a value. All other attributes are optional.

https://developer.cisco.com/docs/identity-services-engine/latest/#!sgt

If you look here https://registry.terraform.io/providers/CiscoISE/ciscoise/latest/docs/resources/sgt 

it says the required is "parameters (Block List, Min:1, Max:1).  What does this mean?  Please update so we don't' have to go to multiple websites to find out what is a required attribute.

**Comment by fmunozmiranda** [comment]
@RyanMBess , parameters is only a container for ISE API parameters. We update documentation to especify it more. Tell us if it is ok for you.
