### ISSUE TITLE
Update ciscoise_network_access_policy_set fails

### ISSUE THREAD

**Issue by wiwa1978** [CiscoISE/terraform-provider-ciscoise#53]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?

**Describe the bug**
Creating a network access pollicy set works correctly. When you try to update the policy, it fails.

This is the resource used to create the network access policy set:
```
resource "ciscoise_network_access_policy_set" "example" {
  provider = ciscoise
  parameters {
    condition {
      condition_type = "ConditionReference"
      is_negate      = false
      name           = "Wired_MAB"
      id             = "9aab0da7-e3e3-4cd7-81c2-18c3ebbe6a96"
      description    = "A condition to match MAC Authentication Bypass service based authentication requests from switches, according to the corresponding MAB attributes defined in the device profile."
    }
    default      = "false"
    description  = "New Policy Set test 1"
    hit_counts   = 0
    is_proxy     = "false"
    name         = "New Policy Set 1"
    rank         = 0
    service_name = "Default Network Access"
    state        = "disabled"
  }
}
```
It creates the network access policy set correctly. When I then want to update the policy set by setting the state to enabled, it fails with the following message:

```
 Error: Failure when executing UpdateNetworkAccessPolicySetByID
│ 
│   with ciscoise_network_access_policy_set.example,
│   on network_access_policy_set.tf line 9, in resource "ciscoise_network_access_policy_set" "example":
│    9: resource "ciscoise_network_access_policy_set" "example" {
│ 
│ error with operation UpdateNetworkAccessPolicySetById
│ {
│   "message" : "request has bad input format in the body",
│   "code" : 400
│ }
```

**Expected behavior**
It should successfully set the network access policy set to enabled.

**Environment (please complete the following information):**

- ISE version and patch: 3.1.0.518
- Terraform version: Terraform v1.2.3
- ISE provider version: 0.6.7-beta

**Comment by fmunozmiranda** [comment]
Hey @wiwa1978 there's a new version of provider (0.6.8-beta), test it again let us know if it works for you.

**Comment by wiwa1978** [comment]
Fixed!
