### ISSUE TITLE
ISE 3.1 P1 API s

### ISSUE THREAD

**Issue by ragu2k8** [CiscoISE/terraform-provider-ciscoise#7]
is it in pipeline to support APIs released as part of ISE 3.1 P1?

**Comment by jbogarin** [comment]
@ragu2k8 work is currently underway to support ISE 3.1 P1. The terraform provider should be up to date in the following 2 to 3 weeks.

**Comment by ragu2k8** [comment]
appreciate it. Thanks.

**Comment by jbogarin** [comment]
I'll update this issue once the new version is published.

**Comment by wastorga** [comment]
I am closing the issue. The versions from "0.1.0-rc" have support for ISE 3.1.1 APIs.
