### ISSUE TITLE
ciscoise_internal_user import results in Error

### ISSUE THREAD

**Issue by criedl01** [CiscoISE/terraform-provider-ciscoise#88]
**Prerequisites**
* [ yes ] Have you tested the operation in the API directly?
* [ yes ] Do you have the latest Terraform provider version?
* [ yes ] Review the [compatibility matrix](https://github.com/CiscoISE/terraform-provider-ciscoise/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
ciscoise_internal_user import unconditionally results in Error: Failure when setting GetInternalUserByName response
parameters.0.custom_attributes: '' expected type 'string', got unconvertible type
'isegosdk.ResponseInternalUserGetInternalUserByNameInternalUserCustomAttributes', value: 'map[]'

![image](https://user-images.githubusercontent.com/23128964/226910531-8c1be4f8-cf1e-4480-8918-b666a2687163.png)

Tested with different ISE deployments, different users, import by name or id. The same error is shown when enable_auto_import is true.

**Expected behavior**
Expected successful import of internal user

**Screenshots**
![image](https://user-images.githubusercontent.com/23128964/226912117-92cceed3-1419-40dd-b9dd-97a41f009072.png)

**Environment (please complete the following information):**
* ISE version and patch: 2.7 p6, 3.1 p1, 3.2 p1
* Terraform version: v1.3.9
* ISE provider version: v0.6.18-beta
* OS version: Windows 10 Pro 22H2

**Additional context**
currently no known workaround exists

**Comment by fmunozmiranda** [comment]
Hi, @criedl01 please try it again with the new provider version and let me know how does it go.

**Comment by fmunozmiranda** [comment]
closed due inactivity
