### ISSUE TITLE
Allowed Protocols Mandatory 5G Field Error

### ISSUE THREAD

**Issue by jon-humphries** [CiscoISE/terraform-provider-ciscoise#89]
Using the latest Terraform Provider with ISE 3.2, we are trying to configure allowed protocols.

https://developer.cisco.com/docs/identity-services-engine/latest/#!allowedprotocols

The terraform module needs to be ammened to include a new mandatory field for 5G.

![image](https://user-images.githubusercontent.com/16271762/226964609-fd395271-7730-4c40-acac-dd5a904be766.png)

**Describe the bug**
When applying the allowed protocols we need to include a response for the 5G mandatory field either True/False. If we do this via the API it works correctly as long as the mandatory 5G field is included.

**Environment (please complete the following information):**
* ISE version and patch: 3.2 Patch 1

**Comment by grg1bbs** [comment]
Hi @jon-humphries. I don't believe the provider has been validated against 3.2 yet. There have been various API changes between 3.1 and 3.2 that have broken both TF and Ansible workflows.
Ideally, the issues should be fixed with the API rather than making the TF provider differentiate between ISE versions.
I previously filed this bug related to the issue you are seeing with the Allowed Protocols:
https://bst.cloudapps.cisco.com/bugsearch/bug/CSCwe14317

**Comment by jon-humphries** [comment]
Thanks @grg1bbs  makes sense and appreciate you highlighting this bug. Could someone tag/label this as an API-Bug please, so we can track it for future reference ?

**Comment by grg1bbs** [comment]
@fmunozmiranda, are you able to tag this as api-bug please?

**Comment by kuba-mazurkiewicz** [comment]
hey, isn't better to add this five_g as optional parameter to terraform provider instead of tagging that as api-bug ? You could then use five_g parameter when using allowed_protocols resource in 3.2 and simply not use it when working with 3.1 ISE version. This is easy fix.

**Comment by grg1bbs** [comment]
@jon-humphries, I can confirm that this bug is resolved in ISE 3.2 p4 (which should be released to the public by the end of this week) and the TF resource works. The 'fiveG' attribute has been changed to optional in the API.

**Comment by grg1bbs** [comment]
@fmunozmiranda, I believe you can close this issue. The API bug has been fixed in ISE 3.2 patch 4
