### ISSUE TITLE
ciscoise_network_device_group missing other namen

### ISSUE THREAD

**Issue by larsrei** [CiscoISE/terraform-provider-ciscoise#94]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/CiscoISE/terraform-provider-ciscoise/tree/main#compatibility-matrix)  ISE 3.1 patch 6before opening an issue. 

**Describe the bug**
Try to build a network devices group
```
resource "ciscoise_network_device_group" "example" {
  provider = ciscoise
  parameters {

    description = "string"
    id          = "string"
    name        = "string"
    ndgtype     = "string"
  }
}
```
Then you become follow error:
```
Error: Failure when executing CreateNetworkDeviceGroup
│ 
│   with ciscoise_network_device_group.device_group_create["Device Type#All Device Types#LRTest#SuperDev"],
│   on main.tf line 2, in resource "ciscoise_network_device_group" "device_group_create":
│    2: resource "ciscoise_network_device_group" "device_group_create" {
│ 
│ error with operation CreateNetworkDeviceGroup
│ {
│   "ERSResponse" : {
│     "operation" : "POST-create-networkdevicegroup",
│     "messages" : [ {
│       "title" : "Validation Error - Mandatory fields missing: [othername]",
│       "type" : "ERROR",
│       "code" : "Application resource validation exception"
│     } ],
│     "link" : {
│       "rel" : "related",
│       "href" : "https://myServerMask:9060/ers/config/networkdevicegroup",
│       "type" : "application/xml"
│     }
│   }
│ }
```

The ERS API say you need the paramter:

Attribute | Type | Required | Default value | Description
-- | -- | -- | -- | --
name | String | Yes |   | Resource name
id | String | No |   | Resource UUID, mandatory for update
description | String | No |   |  
othername | String | Yes |   | This field holds the Network Device Group Hierarchy (A.K.A NDG Type)

**Expected behavior**
ndgtype     = "string" ist the othername paramater but this is not working.
Not really shure what ndgtype should be maybe "Location" or "Type"

Taking ndgtype as othername is not working

```
│ Error: Failure when executing UpdateNetworkDeviceGroupByID
│ 
│   with ciscoise_network_device_group.device_group_create["Device Type#All Device Types#LRTest"],
│   on main.tf line 2, in resource "ciscoise_network_device_group" "device_group_create":
│    2: resource "ciscoise_network_device_group" "device_group_create" {
│ 
│ error with operation UpdateNetworkDeviceGroupById
│ {
│   "ERSResponse" : {
│     "operation" : "PUT-update-networkdevicegroup",
│     "messages" : [ {
│       "title" : "Resource Initialization Failed: Invalid JSON: Unrecognized field \"ndgtype\" (Class network.NetworkDeviceGroup), not marked as ignorable\n ",
│       "type" : "ERROR",
│       "code" : "Application resource validation exception"
│     } ],
│     "link" : {
│       "rel" : "related",
│       "href" : "https://isekonvdcmas01.ka.de.dm-drogeriemarkt.com:9060/ers/config/networkdevicegroup/28ccc190-0b54-11ee-921f-8edba861ae07",
│       "type" : "application/xml"
│     }
│   }
│ }
```

**Environment (please complete the following information):**
* ISE version and patch:  3.1 patch 6
* Terraform version: v1.2.9
* ISE provider version: 0.6.18-beta
* OS version:  MAC OS

**Comment by fmunozmiranda** [comment]
@larsrei please try it again with `0.6.20-beta` and let us know how does it go.

**Comment by larsrei** [comment]
@fmunozmiranda I try it but not working. Not sure if I use all option rigth:

> terraform apply
ciscoise_network_device_group.device_group_create["Device Type#All Device Types#LRTest"]: Refreshing state... [id=id:=28ccc190-0b54-11ee-921f-8edba861ae07\name:=Device Type#All Device Types#LRTest]
╷
│ Error: Failure when setting GetNetworkDeviceGroupByID response
│ 
│   with ciscoise_network_device_group.device_group_create["Device Type#All Device Types#LRTest"],
│   on main.tf line 2, in resource "ciscoise_network_device_group" "device_group_create":
│    2: resource "ciscoise_network_device_group" "device_group_create" {
│ 
│ Invalid address to set: []string{"parameters", "0", "ndgtype"}


Terraform code:
# Create Devices Types
resource "ciscoise_network_device_group" "device_group_create" {
  provider = ciscoise
  for_each = var.device_groups
  parameters {
    description = each.value["description"]
    name        = each.key
    othername   = each.value["othername"]
  }
}
Variable:
# All devcies types who are needed
variable "device_groups" {
  type = map(object({
    description = string
    othername     = string
  }))
  default = {
    "Device Type#All Device Types#LRTest"          = { description : "Lars Test", othername : "Device Type#All Device Types" }
    "Device Type#All Device Types#LRTest#SuperDev" = { description : "Super Device", othername : "Device Type#All Device Types#LRTest" }
  }
}

**Comment by fmunozmiranda** [comment]
Hi, @larsrei please try it again with the new provider version and let me know how does it go.

**Comment by larsrei** [comment]
Hi,

still error:
`Plan: 1 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

ciscoise_network_device_group.device_group_create["Device Type#All Device Types#LRTest#SuperDev"]: Creating...
ciscoise_network_device_group.device_group_create["Device Type#All Device Types#LRTest"]: Modifying... [id=id:=28ccc190-0b54-11ee-921f-8edba861ae07\name:=Device Type#All Device Types#LRTest]
╷
│ Error: Failure when executing UpdateNetworkDeviceGroupByID
│ 
│   with ciscoise_network_device_group.device_group_create["Device Type#All Device Types#LRTest"],
│   on main.tf line 2, in resource "ciscoise_network_device_group" "device_group_create":
│    2: resource "ciscoise_network_device_group" "device_group_create" {
│ 
│ error with operation UpdateNetworkDeviceGroupById
│ {
│   "ERSResponse" : {
│     "operation" : "PUT-update-networkdevicegroup",
│     "messages" : [ {
│       "title" : "Validation Error - Illegal values: [The request content has an invalid type(othername). Please verify type(othername) contains alphanumeric characters, underscore, minus signs, dot only., The name's first part (before the first pound sign delimiter) should be equal to group's type(othername) provided.]",
│       "type" : "ERROR",
│       "code" : "Application resource validation exception"
│     } ],
│     "link" : {
│       "rel" : "related",
│       "href" : "https://server:9060/ers/config/networkdevicegroup/28ccc190-0b54-11ee-921f-8edba861ae07",
│       "type" : "application/xml"
│     }
│   }
│ }
╵
╷
│ Error: Failure when executing CreateNetworkDeviceGroup
│ 
│   with ciscoise_network_device_group.device_group_create["Device Type#All Device Types#LRTest#SuperDev"],
│   on main.tf line 2, in resource "ciscoise_network_device_group" "device_group_create":
│    2: resource "ciscoise_network_device_group" "device_group_create" {
│ 
│ error with operation CreateNetworkDeviceGroup
│ {
│   "ERSResponse" : {
│     "operation" : "POST-create-networkdevicegroup",
│     "messages" : [ {
│       "title" : "Validation Error - Illegal values: [The request content has an invalid type(othername). Please verify type(othername) contains alphanumeric characters, underscore, minus signs, dot only., The name's first part (before the first pound sign delimiter) should be equal to group's type(othername) provided.]",
│       "type" : "ERROR",
│       "code" : "Application resource validation exception"
│     } ],
│     "link" : {
│       "rel" : "related",
│       "href" : "https://server:9060/ers/config/networkdevicegroup",
│       "type" : "application/xml"
│     }
│   }
│ }
`

**Comment by larsrei** [comment]
@fmunozmiranda  you are right! 

terraform apply -parallelism=1  

is important.

Result:
`Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

ciscoise_network_device_group.device_group_create["Device Type#All Device Types#LRTest"]: Creating...
ciscoise_network_device_group.device_group_create["Device Type#All Device Types#LRTest"]: Creation complete after 1s [id=id:=4ef9e1b0-1683-11ee-9793-660220509ceb\name:=Device Type#All Device Types#LRTest]
ciscoise_network_device_group.device_group_create["Device Type#All Device Types#LRTest#SuperDev"]: Creating...
ciscoise_network_device_group.device_group_create["Device Type#All Device Types#LRTest#SuperDev"]: Creation complete after 0s [id=id:=4f3786f0-1683-11ee-9793-660220509ceb\name:=Device Type#All Device Types#LRTest#SuperDev]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
`
